fix workflows lan 7

diff --git a/.github/workflows/deploy-api.yml b/.github/workflows/deploy-api.yml
--- a/.github/workflows/deploy-api.yml
+++ b/.github/workflows/deploy-api.yml
@@ -20,9 +20,30 @@ jobs:
           password: ${{ secrets.SERVER_PASSWORD }}
           port: ${{ secrets.SERVER_PORT }}
           script: |
-            cd ~/dev/phuoggiang-clone/backend
+            # Clone the repository if not already cloned
+            if [ ! -d "phuoggiang-clone" ]; then
+              git clone https://github.com/nd-thuong/phuoggiang-clone.git
+            fi
+
+            cd phuoggiang-clone/backend
+
+            # Ensure we are in a git repository
+            if [ ! -d ".git" ]; then
+              echo "Not a git repository."
+              exit 1
+            fi
+
             git checkout main
             git fetch -p
             git pull
+
+            # Install Node.js and npm if not installed
+            if ! command -v npm &> /dev/null; then
+              echo "npm could not be found, installing Node.js and npm"
+              curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
+              sudo apt-get install -y nodejs
+            fi
+
+            npm install
             npm run build
             npm run start:prod
